"""Enterprise RBAC service."""

from __future__ import annotations

from collections import defaultdict

from agentfabric.errors import AuthorizationError


class RbacService:
    """Role-based authorization for runtime/registry/billing actions."""

    ROLE_PERMISSIONS = {
        "admin": {
            "tenant.manage",
            "tenant.settings.manage",
            "team.manage",
            "members.manage",
            "quotas.read",
            "quotas.manage",
            "usage.read",
            "registry.publish",
            "registry.install",
            "registry.read",
            "registry.read_private",
            "marketplace.publish",
            "marketplace.install",
            "marketplace.read",
            "marketplace.review",
            "billing.read",
            "billing.write",
            "billing.manage",
            "agent.create",
            "agent.execute",
            "runtime.run",
            "mesh.send",
            "mesh.broadcast",
            "workflow.start",
            "workflow.read",
            "workflow.recover",
            "agents.read",
            "reputation.read",
            "events.read",
            "memory.read",
            "memory.write",
            "memory.delete",
            "persistence.read",
            "audit.read",
            "audit.write",
            "audit.export",
            "rbac.assign_role",
            "ops.backup.read",
            "ops.backup.write",
            "metrics.read",
            "governance.manage",
            "governance.read",
            "governance.propose",
            "governance.vote",
            "governance.execute",
            "governance.approve",
            "runtime.jobs.read",
            "runtime.jobs.manage",
            "runtime.workers.manage",
            "runtime.schedules.manage",
            "federation.manage",
            "federation.read",
            "federation.message",
            "federation.delegate",
            "connectors.read",
            "connectors.manage",
            "tools.read",
            "tools.manage",
            "tools.execute",
            "evaluations.read",
            "evaluations.manage",
            "feedback.read",
            "feedback.write",
            "economics.read",
            "economics.manage",
            "observability:read",
            "observability:write",
            "health:read",
            "drift:read",
            "anomaly:read",
            "recommendations:read",
            "recommendations:approve",
            "connectors:read",
            "connectors:write",
            "connectors:execute",
            "connectors:admin",
            "credentials:read",
            "credentials:write",
            "credentials:rotate",
            "gmail.read",
            "gmail.send",
            "calendar.read",
            "calendar.write",
            "github.read",
            "github.write",
            "jira.read",
            "jira.write",
            "slack.read",
            "slack.write",
            "servicenow.read",
            "servicenow.write",
            "s3.read",
            "s3.write",
            "custom_http.execute",
            "teams.read",
            "teams.write",
            "salesforce.read",
            "salesforce.write",
            "sharepoint.read",
            "sharepoint.write",
        },
        "developer": {
            "agents.read",
            "agent.create",
            "agent.execute",
            "workflow.start",
            "workflow.read",
            "workflow.recover",
            "memory.read",
            "memory.write",
            "events.read",
            "usage.read",
            "registry.publish",
            "registry.install",
            "registry.read",
            "registry.read_private",
            "marketplace.publish",
            "marketplace.install",
            "marketplace.read",
            "marketplace.review",
            "runtime.run",
            "mesh.send",
            "mesh.broadcast",
            "workflow.start",
            "workflow.read",
            "workflow.recover",
            "agents.read",
            "reputation.read",
            "events.read",
            "memory.read",
            "memory.write",
            "memory.delete",
            "persistence.read",
            "audit.read",
            "governance.read",
            "governance.propose",
            "governance.vote",
            "runtime.jobs.read",
            "runtime.jobs.manage",
            "runtime.schedules.manage",
            "federation.read",
            "federation.message",
            "federation.delegate",
            "connectors.read",
            "connectors.manage",
            "tools.read",
            "tools.manage",
            "tools.execute",
            "evaluations.read",
            "evaluations.manage",
            "feedback.read",
            "feedback.write",
            "economics.read",
            "observability:read",
            "observability:write",
            "health:read",
            "drift:read",
            "anomaly:read",
            "recommendations:read",
            "connectors:read",
            "connectors:write",
            "connectors:execute",
            "credentials:read",
            "credentials:write",
            "credentials:rotate",
            "gmail.read",
            "gmail.send",
            "calendar.read",
            "calendar.write",
            "github.read",
            "github.write",
            "jira.read",
            "jira.write",
            "slack.read",
            "slack.write",
            "servicenow.read",
            "servicenow.write",
            "s3.read",
            "s3.write",
            "custom_http.execute",
            "teams.read",
            "teams.write",
            "salesforce.read",
            "salesforce.write",
            "sharepoint.read",
            "sharepoint.write",
        },
        "viewer": {
            "agents.read",
            "workflow.read",
            "memory.read",
            "events.read",
            "reputation.read",
            "usage.read",
            "registry.install",
            "marketplace.install",
            "marketplace.read",
            "billing.read",
            "audit.read",
            "governance.read",
            "runtime.jobs.read",
            "federation.read",
            "connectors.read",
            "tools.read",
            "evaluations.read",
            "feedback.read",
            "economics.read",
            "observability:read",
            "health:read",
            "drift:read",
            "anomaly:read",
            "recommendations:read",
            "connectors:read",
            "credentials:read",
        },
        "owner": set(),
        "operator": {
            "agent.execute",
            "runtime.run",
            "mesh.send",
            "mesh.broadcast",
            "workflow.start",
            "workflow.read",
            "workflow.recover",
            "events.read",
            "memory.read",
            "usage.read",
            "governance.read",
            "governance.propose",
            "governance.execute",
            "runtime.jobs.read",
            "runtime.jobs.manage",
            "runtime.workers.manage",
            "runtime.schedules.manage",
            "federation.read",
            "federation.message",
            "federation.delegate",
            "connectors.read",
            "connectors.manage",
            "tools.read",
            "tools.manage",
            "tools.execute",
            "evaluations.read",
            "evaluations.manage",
            "feedback.read",
            "feedback.write",
            "economics.read",
            "economics.manage",
            "observability:read",
            "observability:write",
            "health:read",
            "drift:read",
            "anomaly:read",
            "recommendations:read",
            "recommendations:approve",
            "connectors:read",
            "connectors:write",
            "connectors:execute",
            "credentials:read",
            "gmail.read",
            "gmail.send",
            "calendar.read",
            "calendar.write",
            "github.read",
            "github.write",
            "jira.read",
            "jira.write",
            "slack.read",
            "slack.write",
            "servicenow.read",
            "servicenow.write",
            "s3.read",
            "s3.write",
            "custom_http.execute",
            "teams.read",
            "teams.write",
            "salesforce.read",
            "salesforce.write",
            "sharepoint.read",
            "sharepoint.write",
        },
        "reviewer": {
            "agents.read",
            "workflow.read",
            "events.read",
            "reputation.read",
            "reviews.write",
            "governance.read",
            "governance.vote",
            "governance.approve",
            "runtime.jobs.read",
            "federation.read",
            "connectors.read",
            "tools.read",
            "evaluations.read",
            "feedback.read",
            "feedback.write",
            "economics.read",
            "observability:read",
            "health:read",
            "drift:read",
            "anomaly:read",
            "recommendations:read",
            "recommendations:approve",
            "connectors:read",
            "credentials:read",
        },
        "billing_admin": {
            "billing.read",
            "billing.write",
            "billing.manage",
            "usage.read",
            "quotas.read",
        },
        "auditor": {
            "agents.read",
            "workflow.read",
            "events.read",
            "audit.read",
            "audit.export",
            "usage.read",
            "reputation.read",
            "governance.read",
            "runtime.jobs.read",
            "federation.read",
            "connectors.read",
            "tools.read",
            "evaluations.read",
            "feedback.read",
            "economics.read",
            "observability:read",
            "health:read",
            "drift:read",
            "anomaly:read",
            "recommendations:read",
            "connectors:read",
            "credentials:read",
        },
        "service_account": {
            "agent.execute",
            "runtime.run",
            "mesh.send",
            "workflow.start",
            "workflow.read",
            "memory.read",
            "memory.write",
            "events.read",
            "governance.read",
            "governance.propose",
            "runtime.jobs.read",
            "runtime.jobs.manage",
            "runtime.workers.manage",
            "federation.read",
            "federation.message",
            "federation.delegate",
            "connectors.read",
            "connectors.manage",
            "tools.read",
            "tools.execute",
            "evaluations.read",
            "feedback.read",
            "feedback.write",
            "economics.read",
            "observability:read",
            "observability:write",
            "health:read",
            "drift:read",
            "anomaly:read",
            "recommendations:read",
            "connectors:read",
            "connectors:execute",
            "credentials:read",
            "gmail.read",
            "calendar.read",
            "github.read",
            "jira.read",
            "slack.read",
            "servicenow.read",
            "s3.read",
            "custom_http.execute",
            "teams.read",
            "salesforce.read",
            "sharepoint.read",
        },
    }

    ROLE_PERMISSIONS["admin"].update({
        "factory:read",
        "factory:write",
        "factory:execute",
        "factory:admin",
        "factory:quality",
    })
    ROLE_PERMISSIONS["developer"].update({
        "factory:read",
        "factory:write",
        "factory:execute",
        "factory:quality",
    })
    ROLE_PERMISSIONS["operator"].update({"factory:read", "factory:execute", "factory:quality"})
    ROLE_PERMISSIONS["viewer"].add("factory:read")
    ROLE_PERMISSIONS["reviewer"].update({"factory:read", "factory:quality"})
    ROLE_PERMISSIONS["auditor"].update({"factory:read", "factory:quality"})
    ROLE_PERMISSIONS["service_account"].update({"factory:read", "factory:execute"})

    renovation_read = {"renovation.estimate.read", "renovation.proposal.read"}
    renovation_write = {"renovation.estimate.write", "renovation.proposal.write"}
    renovation_operations_read = {
        "renovation.jobs.read",
        "renovation.documentation.read",
        "renovation.change_orders.read",
    }
    renovation_operations_write = {
        "renovation.jobs.write",
        "renovation.documentation.write",
        "renovation.change_orders.write",
    }
    renovation_approve = {"renovation.change_orders.approve"}
    ROLE_PERMISSIONS["admin"].update(
        renovation_read | renovation_write | renovation_operations_read | renovation_operations_write | renovation_approve
    )
    ROLE_PERMISSIONS["developer"].update(
        renovation_read | renovation_write | renovation_operations_read | renovation_operations_write
    )
    ROLE_PERMISSIONS["operator"].update(
        renovation_read
        | renovation_write
        | renovation_operations_read
        | renovation_operations_write
        | renovation_approve
    )
    ROLE_PERMISSIONS["reviewer"].update(renovation_read | renovation_operations_read | renovation_approve)
    ROLE_PERMISSIONS["auditor"].update(renovation_read | renovation_operations_read)
    ROLE_PERMISSIONS["viewer"].update(renovation_read | renovation_operations_read)
    ROLE_PERMISSIONS["service_account"].update(
        renovation_read | renovation_write | renovation_operations_read | renovation_operations_write
    )

    ROLE_PERMISSIONS["owner"] = set().union(*ROLE_PERMISSIONS.values()) | {
        "auth.admin",
        "members.manage",
        "tenant.manage",
        "tenant.settings.manage",
        "quotas.manage",
    }

    def __init__(self) -> None:
        self._roles_by_principal: defaultdict[str, set[str]] = defaultdict(set)

    def assign_role(self, principal_id: str, role: str) -> None:
        if role not in self.ROLE_PERMISSIONS:
            raise AuthorizationError(f"unknown role: {role}")
        self._roles_by_principal[principal_id].add(role)

    def check(self, principal_id: str, permission: str) -> None:
        for role in self._roles_by_principal[principal_id]:
            if permission in self.ROLE_PERMISSIONS[role]:
                return
        raise AuthorizationError(f"principal {principal_id} lacks {permission}")
